// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: parser.proto

package parser_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ParseV1Client is the client API for ParseV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParseV1Client interface {
	SendHttp(ctx context.Context, in *ParsingRequest, opts ...grpc.CallOption) (*ParsingResponse, error)
}

type parseV1Client struct {
	cc grpc.ClientConnInterface
}

func NewParseV1Client(cc grpc.ClientConnInterface) ParseV1Client {
	return &parseV1Client{cc}
}

func (c *parseV1Client) SendHttp(ctx context.Context, in *ParsingRequest, opts ...grpc.CallOption) (*ParsingResponse, error) {
	out := new(ParsingResponse)
	err := c.cc.Invoke(ctx, "/parser_v1.ParseV1/SendHttp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParseV1Server is the server API for ParseV1 service.
// All implementations must embed UnimplementedParseV1Server
// for forward compatibility
type ParseV1Server interface {
	SendHttp(context.Context, *ParsingRequest) (*ParsingResponse, error)
	mustEmbedUnimplementedParseV1Server()
}

// UnimplementedParseV1Server must be embedded to have forward compatible implementations.
type UnimplementedParseV1Server struct {
}

func (UnimplementedParseV1Server) SendHttp(context.Context, *ParsingRequest) (*ParsingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHttp not implemented")
}
func (UnimplementedParseV1Server) mustEmbedUnimplementedParseV1Server() {}

// UnsafeParseV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParseV1Server will
// result in compilation errors.
type UnsafeParseV1Server interface {
	mustEmbedUnimplementedParseV1Server()
}

func RegisterParseV1Server(s grpc.ServiceRegistrar, srv ParseV1Server) {
	s.RegisterService(&ParseV1_ServiceDesc, srv)
}

func _ParseV1_SendHttp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParsingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParseV1Server).SendHttp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parser_v1.ParseV1/SendHttp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParseV1Server).SendHttp(ctx, req.(*ParsingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParseV1_ServiceDesc is the grpc.ServiceDesc for ParseV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParseV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parser_v1.ParseV1",
	HandlerType: (*ParseV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHttp",
			Handler:    _ParseV1_SendHttp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parser.proto",
}
